steps:

- task: UseRubyVersion@0
  inputs:
    versionSpec: '= 2.6'

- script: |
    ruby -v
    ridk version
  displayName: 'ruby -v + ridk version'

- script: |
    bash .azure-pipelines\patch_readline.sh
  displayName: 'patch local readline implementation (for https://github.com/bundler/bundler/issues/6907)'

- script: |
    ruby bin/rake spec:deps
  displayName: 'ruby bin/rake spec:deps'

- script: |
    gem install --no-document --conservative rspec_junit_formatter
  displayName: 'gem install rspec_junit_formatter'

- script: |
    ruby -r rspec_junit_formatter bin/rspec --format RspecJunitFormatter -o rspec/bundler-junit-results.xml || exit 0
  displayName: 'ruby bin/rspec'

- task: PublishTestResults@2
  inputs:
    testRunner: JUnit
    testResultsFiles: rspec/bundler-junit-results.xml
  displayName: Publish test results
  condition: succeededOrFailed()
