steps:

- task: UseRubyVersion@0
  inputs:
    versionSpec: '= 2.4'

- script: |
    ruby -v
    ridk version
  displayName: 'ruby -v + ridk version'

- script: |
    mkdir tmp
    cd tmp
    mkdir home
  displayName: 'work around readline crash (for https://github.com/bundler/bundler/issues/6902)'

- script: |
    git apply --ignore-space-change --ignore-whitespace .azure-pipelines\rbreadline.diff --directory=C:/hostedtoolcache/windows/Ruby/2.4.5/x64/lib/ruby/site_ruby --unsafe-paths
  displayName: 'patch local readline implementation (for https://github.com/bundler/bundler/issues/6907)'

- script: |
    ruby bin/rake spec:deps
  displayName: 'ruby bin/rake spec:deps'

- script: |
    gem install --no-document --conservative rspec_junit_formatter
  displayName: 'gem install rspec_junit_formatter'

- script: |
    ruby -r rspec_junit_formatter bin/rspec --format progress --format RspecJunitFormatter -o rspec/bundler-junit-results.xml || exit 0
  displayName: 'ruby bin/rspec'

- task: PublishTestResults@2
  inputs:
    testRunner: JUnit
    testResultsFiles: rspec/bundler-junit-results.xml
  displayName: Publish test results
  condition: succeededOrFailed()
